{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tee-sniper-api.serviceAccountName" . }}
  labels:
    {{- include "tee-sniper-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
