// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/stebennett/tee-sniper/pkg/models"
)

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// AddPlayingPartner mocks base method.
func (m *MockBookingService) AddPlayingPartner(bookingID, partnerID string, slotNumber int, dryRun bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPlayingPartner", bookingID, partnerID, slotNumber, dryRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPlayingPartner indicates an expected call of AddPlayingPartner.
func (mr *MockBookingServiceMockRecorder) AddPlayingPartner(bookingID, partnerID, slotNumber, dryRun interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPlayingPartner", reflect.TypeOf((*MockBookingService)(nil).AddPlayingPartner), bookingID, partnerID, slotNumber, dryRun)
}

// BookTimeSlot mocks base method.
func (m *MockBookingService) BookTimeSlot(timeSlot models.TimeSlot, playingPartners []string, dryRun bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookTimeSlot", timeSlot, playingPartners, dryRun)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookTimeSlot indicates an expected call of BookTimeSlot.
func (mr *MockBookingServiceMockRecorder) BookTimeSlot(timeSlot, playingPartners, dryRun interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookTimeSlot", reflect.TypeOf((*MockBookingService)(nil).BookTimeSlot), timeSlot, playingPartners, dryRun)
}

// GetCourseAvailability mocks base method.
func (m *MockBookingService) GetCourseAvailability(dateStr string) ([]models.TimeSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourseAvailability", dateStr)
	ret0, _ := ret[0].([]models.TimeSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourseAvailability indicates an expected call of GetCourseAvailability.
func (mr *MockBookingServiceMockRecorder) GetCourseAvailability(dateStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourseAvailability", reflect.TypeOf((*MockBookingService)(nil).GetCourseAvailability), dateStr)
}

// Login mocks base method.
func (m *MockBookingService) Login(username, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", username, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockBookingServiceMockRecorder) Login(username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockBookingService)(nil).Login), username, password)
}

// MockSMSService is a mock of SMSService interface.
type MockSMSService struct {
	ctrl     *gomock.Controller
	recorder *MockSMSServiceMockRecorder
}

// MockSMSServiceMockRecorder is the mock recorder for MockSMSService.
type MockSMSServiceMockRecorder struct {
	mock *MockSMSService
}

// NewMockSMSService creates a new mock instance.
func NewMockSMSService(ctrl *gomock.Controller) *MockSMSService {
	mock := &MockSMSService{ctrl: ctrl}
	mock.recorder = &MockSMSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSService) EXPECT() *MockSMSServiceMockRecorder {
	return m.recorder
}

// SendSms mocks base method.
func (m *MockSMSService) SendSms(from, to, body string, dryRun bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSms", from, to, body, dryRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSms indicates an expected call of SendSms.
func (mr *MockSMSServiceMockRecorder) SendSms(from, to, body, dryRun interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSms", reflect.TypeOf((*MockSMSService)(nil).SendSms), from, to, body, dryRun)
}
