apiVersion: v1
kind: Service
metadata:
  name: {{ include "tee-sniper-web.fullname" . }}
  labels: {{- include "tee-sniper-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector: {{- include "tee-sniper-web.selectorLabels" . | nindent 4 }}
