name: Books a Tee-time - Schedule

on:
    schedule:
        - cron: '59 19 * * 5,6'

jobs:
    Book-A-Tee-Time:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup-Go
              uses: actions/setup-go/@v4
              with:
                go-version: '^1.17.13'
            - name: Book
              run: go run cmd/tee-sniper/main.go -u ${{ secrets.Username }} -p ${{ secrets.Pin }} -b ${{ secrets.BaseUrl }} -d 8 -t 11:15 -e 13:15 -r 10
        