name: Books a Tee-time - Schedule

on:
    workflow_dispatch:
        inputs:
            daysAhead:
                description: 'Days Ahead'
                required: true
                default: '7'
            timeStart:
                description: 'Time Start'
                required: true
                default: '11:15'
            timeEnd:
                description: 'Time End'
                required: true
                default: '13:15'

jobs:
    Book-A-Tee-Time:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup-Go
              uses: actions/setup-go/@v4
              with:
                go-version: '^1.17.13'
            - name: Book
              run: go run cmd/tee-sniper/main.go -u ${{ secrets.Username }} -p ${{ secrets.Pin }} -b ${{ secrets.BaseUrl }} -d ${{ inputs.daysAhead }} -t ${{ inputs.timeStart }} -e ${{ inputs.timeEnd }} -r 10
        